/**
 * This class is generated by jOOQ
 */
package com.hascode.model;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>mydb</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.hascode.model.tables.records.AuthorRecord> KEY_AUTHOR_PRIMARY = UniqueKeys0.KEY_AUTHOR_PRIMARY;
	public static final org.jooq.UniqueKey<com.hascode.model.tables.records.BookRecord> KEY_BOOK_PRIMARY = UniqueKeys0.KEY_BOOK_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.hascode.model.tables.records.BookAuthorRelRecord, com.hascode.model.tables.records.BookRecord> BOOK_AUTHOR_REL_IBFK_1 = ForeignKeys0.BOOK_AUTHOR_REL_IBFK_1;
	public static final org.jooq.ForeignKey<com.hascode.model.tables.records.BookAuthorRelRecord, com.hascode.model.tables.records.AuthorRecord> BOOK_AUTHOR_REL_IBFK_2 = ForeignKeys0.BOOK_AUTHOR_REL_IBFK_2;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.hascode.model.tables.records.AuthorRecord> KEY_AUTHOR_PRIMARY = createUniqueKey(com.hascode.model.tables.Author.AUTHOR, com.hascode.model.tables.Author.AUTHOR.ID);
		public static final org.jooq.UniqueKey<com.hascode.model.tables.records.BookRecord> KEY_BOOK_PRIMARY = createUniqueKey(com.hascode.model.tables.Book.BOOK, com.hascode.model.tables.Book.BOOK.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.hascode.model.tables.records.BookAuthorRelRecord, com.hascode.model.tables.records.BookRecord> BOOK_AUTHOR_REL_IBFK_1 = createForeignKey(com.hascode.model.Keys.KEY_BOOK_PRIMARY, com.hascode.model.tables.BookAuthorRel.BOOK_AUTHOR_REL, com.hascode.model.tables.BookAuthorRel.BOOK_AUTHOR_REL.BOOKID);
		public static final org.jooq.ForeignKey<com.hascode.model.tables.records.BookAuthorRelRecord, com.hascode.model.tables.records.AuthorRecord> BOOK_AUTHOR_REL_IBFK_2 = createForeignKey(com.hascode.model.Keys.KEY_AUTHOR_PRIMARY, com.hascode.model.tables.BookAuthorRel.BOOK_AUTHOR_REL, com.hascode.model.tables.BookAuthorRel.BOOK_AUTHOR_REL.AUTHORID);
	}
}
