/**
 * This class is generated by jOOQ
 */
package com.hascode.model;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mydb extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 2006265774;

	/**
	 * The singleton instance of <code>mydb</code>
	 */
	public static final Mydb MYDB = new Mydb();

	/**
	 * No further instances allowed
	 */
	private Mydb() {
		super("mydb");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.hascode.model.tables.Author.AUTHOR,
			com.hascode.model.tables.Book.BOOK,
			com.hascode.model.tables.BookAuthorRel.BOOK_AUTHOR_REL);
	}
}
