/**
 * This class is generated by jOOQ
 */
package com.hascode.model;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in mydb
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table mydb.author
	 */
	public static final com.hascode.model.tables.Author AUTHOR = com.hascode.model.tables.Author.AUTHOR;

	/**
	 * The table mydb.book
	 */
	public static final com.hascode.model.tables.Book BOOK = com.hascode.model.tables.Book.BOOK;

	/**
	 * The table mydb.book_author_rel
	 */
	public static final com.hascode.model.tables.BookAuthorRel BOOK_AUTHOR_REL = com.hascode.model.tables.BookAuthorRel.BOOK_AUTHOR_REL;
}
