/**
 * This class is generated by jOOQ
 */
package com.hascode.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookAuthorRelRecord extends org.jooq.impl.TableRecordImpl<com.hascode.model.tables.records.BookAuthorRelRecord> implements org.jooq.Record2<java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = -1293160135;

	/**
	 * Setter for <code>mydb.book_author_rel.bookid</code>.
	 */
	public void setBookid(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mydb.book_author_rel.bookid</code>.
	 */
	public java.lang.Long getBookid() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>mydb.book_author_rel.authorid</code>.
	 */
	public void setAuthorid(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mydb.book_author_rel.authorid</code>.
	 */
	public java.lang.Long getAuthorid() {
		return (java.lang.Long) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.hascode.model.tables.BookAuthorRel.BOOK_AUTHOR_REL.BOOKID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.hascode.model.tables.BookAuthorRel.BOOK_AUTHOR_REL.AUTHORID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getBookid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getAuthorid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookAuthorRelRecord value1(java.lang.Long value) {
		setBookid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookAuthorRelRecord value2(java.lang.Long value) {
		setAuthorid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookAuthorRelRecord values(java.lang.Long value1, java.lang.Long value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BookAuthorRelRecord
	 */
	public BookAuthorRelRecord() {
		super(com.hascode.model.tables.BookAuthorRel.BOOK_AUTHOR_REL);
	}

	/**
	 * Create a detached, initialised BookAuthorRelRecord
	 */
	public BookAuthorRelRecord(java.lang.Long bookid, java.lang.Long authorid) {
		super(com.hascode.model.tables.BookAuthorRel.BOOK_AUTHOR_REL);

		setValue(0, bookid);
		setValue(1, authorid);
	}
}
