/**
 * This class is generated by jOOQ
 */
package com.hascode.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Author extends org.jooq.impl.TableImpl<com.hascode.model.tables.records.AuthorRecord> {

	private static final long serialVersionUID = 65807069;

	/**
	 * The singleton instance of <code>mydb.author</code>
	 */
	public static final com.hascode.model.tables.Author AUTHOR = new com.hascode.model.tables.Author();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.hascode.model.tables.records.AuthorRecord> getRecordType() {
		return com.hascode.model.tables.records.AuthorRecord.class;
	}

	/**
	 * The column <code>mydb.author.id</code>.
	 */
	public final org.jooq.TableField<com.hascode.model.tables.records.AuthorRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>mydb.author.name</code>.
	 */
	public final org.jooq.TableField<com.hascode.model.tables.records.AuthorRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>mydb.author</code> table reference
	 */
	public Author() {
		this("author", null);
	}

	/**
	 * Create an aliased <code>mydb.author</code> table reference
	 */
	public Author(java.lang.String alias) {
		this(alias, com.hascode.model.tables.Author.AUTHOR);
	}

	private Author(java.lang.String alias, org.jooq.Table<com.hascode.model.tables.records.AuthorRecord> aliased) {
		this(alias, aliased, null);
	}

	private Author(java.lang.String alias, org.jooq.Table<com.hascode.model.tables.records.AuthorRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.hascode.model.Mydb.MYDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.hascode.model.tables.records.AuthorRecord> getPrimaryKey() {
		return com.hascode.model.Keys.KEY_AUTHOR_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.hascode.model.tables.records.AuthorRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.hascode.model.tables.records.AuthorRecord>>asList(com.hascode.model.Keys.KEY_AUTHOR_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.hascode.model.tables.Author as(java.lang.String alias) {
		return new com.hascode.model.tables.Author(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.hascode.model.tables.Author rename(java.lang.String name) {
		return new com.hascode.model.tables.Author(name, null);
	}
}
