/**
 * This class is generated by jOOQ
 */
package com.hascode.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookAuthorRel extends org.jooq.impl.TableImpl<com.hascode.model.tables.records.BookAuthorRelRecord> {

	private static final long serialVersionUID = 196266767;

	/**
	 * The singleton instance of <code>mydb.book_author_rel</code>
	 */
	public static final com.hascode.model.tables.BookAuthorRel BOOK_AUTHOR_REL = new com.hascode.model.tables.BookAuthorRel();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.hascode.model.tables.records.BookAuthorRelRecord> getRecordType() {
		return com.hascode.model.tables.records.BookAuthorRelRecord.class;
	}

	/**
	 * The column <code>mydb.book_author_rel.bookid</code>.
	 */
	public final org.jooq.TableField<com.hascode.model.tables.records.BookAuthorRelRecord, java.lang.Long> BOOKID = createField("bookid", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>mydb.book_author_rel.authorid</code>.
	 */
	public final org.jooq.TableField<com.hascode.model.tables.records.BookAuthorRelRecord, java.lang.Long> AUTHORID = createField("authorid", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>mydb.book_author_rel</code> table reference
	 */
	public BookAuthorRel() {
		this("book_author_rel", null);
	}

	/**
	 * Create an aliased <code>mydb.book_author_rel</code> table reference
	 */
	public BookAuthorRel(java.lang.String alias) {
		this(alias, com.hascode.model.tables.BookAuthorRel.BOOK_AUTHOR_REL);
	}

	private BookAuthorRel(java.lang.String alias, org.jooq.Table<com.hascode.model.tables.records.BookAuthorRelRecord> aliased) {
		this(alias, aliased, null);
	}

	private BookAuthorRel(java.lang.String alias, org.jooq.Table<com.hascode.model.tables.records.BookAuthorRelRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.hascode.model.Mydb.MYDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.hascode.model.tables.records.BookAuthorRelRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.hascode.model.tables.records.BookAuthorRelRecord, ?>>asList(com.hascode.model.Keys.BOOK_AUTHOR_REL_IBFK_1, com.hascode.model.Keys.BOOK_AUTHOR_REL_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.hascode.model.tables.BookAuthorRel as(java.lang.String alias) {
		return new com.hascode.model.tables.BookAuthorRel(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.hascode.model.tables.BookAuthorRel rename(java.lang.String name) {
		return new com.hascode.model.tables.BookAuthorRel(name, null);
	}
}
