/**
 * This class is generated by jOOQ
 */
package com.hascode.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Book extends org.jooq.impl.TableImpl<com.hascode.model.tables.records.BookRecord> {

	private static final long serialVersionUID = -687687908;

	/**
	 * The singleton instance of <code>mydb.book</code>
	 */
	public static final com.hascode.model.tables.Book BOOK = new com.hascode.model.tables.Book();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.hascode.model.tables.records.BookRecord> getRecordType() {
		return com.hascode.model.tables.records.BookRecord.class;
	}

	/**
	 * The column <code>mydb.book.id</code>.
	 */
	public final org.jooq.TableField<com.hascode.model.tables.records.BookRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>mydb.book.title</code>.
	 */
	public final org.jooq.TableField<com.hascode.model.tables.records.BookRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>mydb.book</code> table reference
	 */
	public Book() {
		this("book", null);
	}

	/**
	 * Create an aliased <code>mydb.book</code> table reference
	 */
	public Book(java.lang.String alias) {
		this(alias, com.hascode.model.tables.Book.BOOK);
	}

	private Book(java.lang.String alias, org.jooq.Table<com.hascode.model.tables.records.BookRecord> aliased) {
		this(alias, aliased, null);
	}

	private Book(java.lang.String alias, org.jooq.Table<com.hascode.model.tables.records.BookRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.hascode.model.Mydb.MYDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.hascode.model.tables.records.BookRecord> getPrimaryKey() {
		return com.hascode.model.Keys.KEY_BOOK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.hascode.model.tables.records.BookRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.hascode.model.tables.records.BookRecord>>asList(com.hascode.model.Keys.KEY_BOOK_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.hascode.model.tables.Book as(java.lang.String alias) {
		return new com.hascode.model.tables.Book(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.hascode.model.tables.Book rename(java.lang.String name) {
		return new com.hascode.model.tables.Book(name, null);
	}
}
